<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" total="10" passed="6">
  <reporter-output>
    <line>
      <![CDATA[testTwo-Log Message five;]]>
    </line>
    <line>
      <![CDATA[testTwo-Log Message four;]]>
    </line>
    <line>
      <![CDATA[testTwo-Log Message five;]]>
    </line>
    <line>
      <![CDATA[testTwo-Log Message four;]]>
    </line>
    <line>
      <![CDATA[testOne-Log Message one]]>
    </line>
    <line>
      <![CDATA[testOne-Log Message one moreeeeeeee;]]>
    </line>
    <line>
      <![CDATA[testThree-Log Message Three;]]>
    </line>
    <line>
      <![CDATA[testTwo-Log Message Two;]]>
    </line>
    <line>
      <![CDATA[testOne-Log Message one]]>
    </line>
    <line>
      <![CDATA[testOne-Log Message one moreeeeeeee;]]>
    </line>
    <line>
      <![CDATA[testThree-Log Message Three;]]>
    </line>
    <line>
      <![CDATA[testTwo-Log Message Two;]]>
    </line>
  </reporter-output>
  <suite name="Suite1" duration-ms="35991" started-at="2016-04-02T06:50:13Z" finished-at="2016-04-02T06:50:49Z">
    <groups>
    </groups>
    <test name="Regression1" duration-ms="35184" started-at="2016-04-02T06:50:13Z" finished-at="2016-04-02T06:50:48Z">
      <class name="tests.ITestListenerDemoEx">
        <test-method status="PASS" signature="createDriver(java.lang.String)[pri:0, instance:tests.ITestListenerDemoEx@70a9f84e]" name="createDriver" is-config="true" duration-ms="1687" started-at="2016-04-02T12:20:13Z" finished-at="2016-04-02T12:20:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createDriver -->
        <test-method status="PASS" signature="launchApplication()[pri:0, instance:tests.ITestListenerDemoEx@70a9f84e]" name="launchApplication" is-config="true" duration-ms="15179" started-at="2016-04-02T12:20:15Z" depends-on-methods="services.TestBase.createDriver" finished-at="2016-04-02T12:20:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method status="FAIL" signature="testFive()[pri:0, instance:tests.ITestListenerDemoEx@70a9f84e]" name="testFive" duration-ms="6" started-at="2016-04-02T12:20:30Z" finished-at="2016-04-02T12:20:30Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at tests.ITestListenerDemoEx.testFive(ITestListenerDemoEx.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[testTwo-Log Message five;]]>
            </line>
          </reporter-output>
        </test-method> <!-- testFive -->
        <test-method status="PASS" signature="testFour()[pri:0, instance:tests.ITestListenerDemoEx@70a9f84e]" name="testFour" duration-ms="1" started-at="2016-04-02T12:20:30Z" finished-at="2016-04-02T12:20:30Z">
          <reporter-output>
            <line>
              <![CDATA[testTwo-Log Message four;]]>
            </line>
          </reporter-output>
        </test-method> <!-- testFour -->
        <test-method status="PASS" signature="testOne()[pri:0, instance:tests.ITestListenerDemoEx@70a9f84e]" name="testOne" duration-ms="18290" started-at="2016-04-02T12:20:30Z" finished-at="2016-04-02T12:20:48Z">
          <reporter-output>
            <line>
              <![CDATA[testOne-Log Message one]]>
            </line>
            <line>
              <![CDATA[testOne-Log Message one moreeeeeeee;]]>
            </line>
          </reporter-output>
        </test-method> <!-- testOne -->
        <test-method status="FAIL" signature="testThree()[pri:0, instance:tests.ITestListenerDemoEx@70a9f84e]" name="testThree" duration-ms="2" started-at="2016-04-02T12:20:48Z" finished-at="2016-04-02T12:20:48Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at tests.ITestListenerDemoEx.testThree(ITestListenerDemoEx.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[testThree-Log Message Three;]]>
            </line>
          </reporter-output>
        </test-method> <!-- testThree -->
        <test-method status="PASS" signature="testTwo()[pri:0, instance:tests.ITestListenerDemoEx@70a9f84e]" name="testTwo" duration-ms="0" started-at="2016-04-02T12:20:48Z" finished-at="2016-04-02T12:20:48Z">
          <reporter-output>
            <line>
              <![CDATA[testTwo-Log Message Two;]]>
            </line>
          </reporter-output>
        </test-method> <!-- testTwo -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:tests.ITestListenerDemoEx@70a9f84e]" name="tearDown" is-config="true" duration-ms="0" started-at="2016-04-02T12:20:48Z" finished-at="2016-04-02T12:20:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.ITestListenerDemoEx -->
    </test> <!-- Regression1 -->
    <test name="Regression2" duration-ms="35991" started-at="2016-04-02T06:50:13Z" finished-at="2016-04-02T06:50:49Z">
      <class name="tests.ITestListenerDemoEx">
        <test-method status="PASS" signature="createDriver(java.lang.String)[pri:0, instance:tests.ITestListenerDemoEx@16267862]" name="createDriver" is-config="true" duration-ms="1689" started-at="2016-04-02T12:20:13Z" finished-at="2016-04-02T12:20:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createDriver -->
        <test-method status="PASS" signature="launchApplication()[pri:0, instance:tests.ITestListenerDemoEx@16267862]" name="launchApplication" is-config="true" duration-ms="31952" started-at="2016-04-02T12:20:15Z" depends-on-methods="services.TestBase.createDriver" finished-at="2016-04-02T12:20:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method status="FAIL" signature="testFive()[pri:0, instance:tests.ITestListenerDemoEx@16267862]" name="testFive" duration-ms="2" started-at="2016-04-02T12:20:47Z" finished-at="2016-04-02T12:20:47Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at tests.ITestListenerDemoEx.testFive(ITestListenerDemoEx.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[testTwo-Log Message five;]]>
            </line>
          </reporter-output>
        </test-method> <!-- testFive -->
        <test-method status="PASS" signature="testFour()[pri:0, instance:tests.ITestListenerDemoEx@16267862]" name="testFour" duration-ms="0" started-at="2016-04-02T12:20:47Z" finished-at="2016-04-02T12:20:47Z">
          <reporter-output>
            <line>
              <![CDATA[testTwo-Log Message four;]]>
            </line>
          </reporter-output>
        </test-method> <!-- testFour -->
        <test-method status="PASS" signature="testOne()[pri:0, instance:tests.ITestListenerDemoEx@16267862]" name="testOne" duration-ms="2338" started-at="2016-04-02T12:20:47Z" finished-at="2016-04-02T12:20:49Z">
          <reporter-output>
            <line>
              <![CDATA[testOne-Log Message one]]>
            </line>
            <line>
              <![CDATA[testOne-Log Message one moreeeeeeee;]]>
            </line>
          </reporter-output>
        </test-method> <!-- testOne -->
        <test-method status="FAIL" signature="testThree()[pri:0, instance:tests.ITestListenerDemoEx@16267862]" name="testThree" duration-ms="1" started-at="2016-04-02T12:20:49Z" finished-at="2016-04-02T12:20:49Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at tests.ITestListenerDemoEx.testThree(ITestListenerDemoEx.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[testThree-Log Message Three;]]>
            </line>
          </reporter-output>
        </test-method> <!-- testThree -->
        <test-method status="PASS" signature="testTwo()[pri:0, instance:tests.ITestListenerDemoEx@16267862]" name="testTwo" duration-ms="1" started-at="2016-04-02T12:20:49Z" finished-at="2016-04-02T12:20:49Z">
          <reporter-output>
            <line>
              <![CDATA[testTwo-Log Message Two;]]>
            </line>
          </reporter-output>
        </test-method> <!-- testTwo -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:tests.ITestListenerDemoEx@16267862]" name="tearDown" is-config="true" duration-ms="0" started-at="2016-04-02T12:20:49Z" finished-at="2016-04-02T12:20:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.ITestListenerDemoEx -->
    </test> <!-- Regression2 -->
  </suite> <!-- Suite1 -->
</testng-results>
