<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MHYDIT1023822" name="Regression1" tests="5" failures="2" timestamp="2 Apr 2016 06:50:48 GMT" time="35.184" errors="0">
  <testcase name="testFive" time="0.006" classname="tests.ITestListenerDemoEx">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at tests.ITestListenerDemoEx.testFive(ITestListenerDemoEx.java:50)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testFive -->
  <testcase name="testFour" time="0.001" classname="tests.ITestListenerDemoEx"/>
  <testcase name="testOne" time="18.29" classname="tests.ITestListenerDemoEx"/>
  <testcase name="testThree" time="0.002" classname="tests.ITestListenerDemoEx">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at tests.ITestListenerDemoEx.testThree(ITestListenerDemoEx.java:38)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testThree -->
  <testcase name="testTwo" time="0.0" classname="tests.ITestListenerDemoEx"/>
</testsuite> <!-- Regression1 -->
